import type { NextPage } from 'next'
import Head from 'next/head'
import styled from "styled-components";
import {NFTDropPage} from "./nft/[id]";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NFTDropPage />
    </Container>
  )
}

export default Home

const Container = styled.div`
  width: 100%;
  height: 100vh;
  display: flex;
  flex-direction: row;
  align-items: flex-start;
  justify-content: flex-start;
  color: white;
`