import type { NextPage } from 'next'
import Head from 'next/head'
import styled from "styled-components";
import {sanityClient} from "../sanity";
import {SanityCollection} from "../types";
import {NFTDropPage} from "../components/NFTDropPage";


type Props = {
    collections: SanityCollection[]
}

const Home: NextPage<Props> = (props: Props) => {

    return (
        <Container>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NFTDropPage collections={props.collections}/>
        </Container>
    )
}

export default Home

export const getServerSideProps = async () => {
    const query = `
    *[_type == "collection"]{
        _id,
        title,
        address,
        description,
        nftCollectionName,
        mainImage,
        previewImage,
        slug {
            current
        },
        creator-> {
            _id,
            name,
            address
        }
    }`
    const collections = await sanityClient.fetch<SanityCollection[]>(query)

    return {
        props: {
            collections
        }
    }
}

const Container = styled.div`
  width: 100%;
  height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  justify-content: flex-start;
  color: white;
`
